id: I3BE10380
legacy_id: P003241
ocr_import_info:
  bdrc_scan_id: W00EGS1016899
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T20:24:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:18:33.651030+00:00'
last_modified: 2022-08-29 18:44:50.452790
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016899
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016899
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤཱཀྱ་མཆོག་ལྡན།
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.9224295109630002
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00EGS1016912:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016912
      total_pages: 744
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I00EGS1016912.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.931353759037208
    legacy_id: v013
  I00EGS1016905:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016905
      total_pages: 754
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00EGS1016905.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9240398426955279
    legacy_id: v006
  I00EGS1016904:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016904
      total_pages: 526
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00EGS1016904.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9161948880684949
    legacy_id: v005
  I00EGS1016920:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016920
      total_pages: 410
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I00EGS1016920.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9252867247606651
    legacy_id: v021
  I00EGS1016921:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016921
      total_pages: 648
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I00EGS1016921.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9274660141932805
    legacy_id: v022
  I00EGS1016916:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016916
      total_pages: 674
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I00EGS1016916.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9329877651804808
    legacy_id: v017
  I00EGS1016900:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016900
      total_pages: 700
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1016900.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9164807864341892
    legacy_id: v001
  I00EGS1016903:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016903
      total_pages: 688
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00EGS1016903.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9194971145559033
    legacy_id: v004
  I00EGS1016901:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016901
      total_pages: 744
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1016901.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.923413351757254
    legacy_id: v002
  I00EGS1016922:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016922
      total_pages: 600
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I00EGS1016922.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9308361907375826
    legacy_id: v023
  I00EGS1016913:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016913
      total_pages: 762
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I00EGS1016913.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9313737188217891
    legacy_id: v014
  I00EGS1016910:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016910
      total_pages: 638
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I00EGS1016910.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9298425306159439
    legacy_id: v011
  I00EGS1016906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016906
      total_pages: 680
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I00EGS1016906.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9312279523491568
    legacy_id: v007
  I00EGS1016918:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016918
      total_pages: 908
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I00EGS1016918.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8999944912349713
    legacy_id: v019
  I00EGS1016923:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016923
      total_pages: 378
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I00EGS1016923.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9396980279751348
    legacy_id: v024
  I00EGS1016911:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016911
      total_pages: 686
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I00EGS1016911.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9237830231996826
    legacy_id: v012
  I00EGS1016902:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016902
      total_pages: 616
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1016902.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8795178255699292
    legacy_id: v003
  I00EGS1016914:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016914
      total_pages: 806
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I00EGS1016914.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9366593763683223
    legacy_id: v015
  I00EGS1016907:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016907
      total_pages: 624
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I00EGS1016907.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9179260007727833
    legacy_id: v008
  I00EGS1016908:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016908
      total_pages: 802
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I00EGS1016908.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9061646283697755
    legacy_id: v009
  I00EGS1016917:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016917
      total_pages: 760
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I00EGS1016917.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9226810888363204
    legacy_id: v018
  I00EGS1016915:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016915
      total_pages: 686
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I00EGS1016915.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9349181487920822
    legacy_id: v016
  I00EGS1016909:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016909
      total_pages: 650
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I00EGS1016909.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9206047506553902
    legacy_id: v010
  I00EGS1016919:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016919
      total_pages: 672
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I00EGS1016919.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.924283145522373
    legacy_id: v020
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
