id: I3BE10380
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:31:47+00:00'
last_modified: '2022-06-07T18:35:55.659026+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016899
  title: གསུང་འབུམ། ཤཱཀྱ་མཆོག་ལྡན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2440':
      image_group_id: I00EGS1016900
      title: ''
      total_pages: 700
      order: 1
      base_file: 2440.txt
    D5A2:
      image_group_id: I00EGS1016901
      title: ''
      total_pages: 744
      order: 2
      base_file: D5A2.txt
    E8E3:
      image_group_id: I00EGS1016902
      title: ''
      total_pages: 616
      order: 3
      base_file: E8E3.txt
    47CC:
      image_group_id: I00EGS1016903
      title: ''
      total_pages: 688
      order: 4
      base_file: 47CC.txt
    F588:
      image_group_id: I00EGS1016904
      title: ''
      total_pages: 526
      order: 5
      base_file: F588.txt
    '4464':
      image_group_id: I00EGS1016905
      title: ''
      total_pages: 754
      order: 6
      base_file: 4464.txt
    '5955':
      image_group_id: I00EGS1016906
      title: ''
      total_pages: 680
      order: 7
      base_file: 5955.txt
    D67A:
      image_group_id: I00EGS1016907
      title: ''
      total_pages: 624
      order: 8
      base_file: D67A.txt
    97A9:
      image_group_id: I00EGS1016908
      title: ''
      total_pages: 802
      order: 9
      base_file: 97A9.txt
    CC28:
      image_group_id: I00EGS1016909
      title: ''
      total_pages: 650
      order: 10
      base_file: CC28.txt
    D780:
      image_group_id: I00EGS1016910
      title: ''
      total_pages: 638
      order: 11
      base_file: D780.txt
    '6788':
      image_group_id: I00EGS1016911
      title: ''
      total_pages: 686
      order: 12
      base_file: 6788.txt
    CCC7:
      image_group_id: I00EGS1016912
      title: ''
      total_pages: 744
      order: 13
      base_file: CCC7.txt
    B444:
      image_group_id: I00EGS1016913
      title: ''
      total_pages: 762
      order: 14
      base_file: B444.txt
    '6219':
      image_group_id: I00EGS1016914
      title: ''
      total_pages: 806
      order: 15
      base_file: 6219.txt
    A575:
      image_group_id: I00EGS1016915
      title: ''
      total_pages: 686
      order: 16
      base_file: A575.txt
    CEE7:
      image_group_id: I00EGS1016916
      title: ''
      total_pages: 674
      order: 17
      base_file: CEE7.txt
    75EB:
      image_group_id: I00EGS1016917
      title: ''
      total_pages: 760
      order: 18
      base_file: 75EB.txt
    0183:
      image_group_id: I00EGS1016918
      title: ''
      total_pages: 908
      order: 19
      base_file: 0183.txt
    89CD:
      image_group_id: I00EGS1016919
      title: ''
      total_pages: 672
      order: 20
      base_file: 89CD.txt
    27BD:
      image_group_id: I00EGS1016920
      title: ''
      total_pages: 410
      order: 21
      base_file: 27BD.txt
    '1432':
      image_group_id: I00EGS1016921
      title: ''
      total_pages: 648
      order: 22
      base_file: 1432.txt
    9D43:
      image_group_id: I00EGS1016922
      title: ''
      total_pages: 600
      order: 23
      base_file: 9D43.txt
    '8444':
      image_group_id: I00EGS1016923
      title: ''
      total_pages: 378
      order: 24
      base_file: 8444.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
