id: P003241
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1016899
  title: གསུང་འབུམ། ཤཱཀྱ་མཆོག་ལྡན
  author: ''
  volumes:
    270e08b1155647deaab9872887082fc2:
      image_group_id: I00EGS1016900
      title: ''
      volume_number: 1
      total_pages: 700
      base_file: v001.txt
    91c4ab81d4eb4e078edd1bbeaa0eca64:
      image_group_id: I00EGS1016901
      title: ''
      volume_number: 2
      total_pages: 744
      base_file: v002.txt
    de43a91082234ba6a451c57a7e601eb5:
      image_group_id: I00EGS1016902
      title: ''
      volume_number: 3
      total_pages: 616
      base_file: v003.txt
    8fb28b0110154fe288fb456194f0cb07:
      image_group_id: I00EGS1016903
      title: ''
      volume_number: 4
      total_pages: 688
      base_file: v004.txt
    6ff1e82beef7457abf7a2ae49ba5488b:
      image_group_id: I00EGS1016904
      title: ''
      volume_number: 5
      total_pages: 526
      base_file: v005.txt
    11dddc7564d24ce69b22b81fbd081a7b:
      image_group_id: I00EGS1016905
      title: ''
      volume_number: 6
      total_pages: 754
      base_file: v006.txt
    0cbaa04b031e4650b66c6e2a6251b98e:
      image_group_id: I00EGS1016906
      title: ''
      volume_number: 7
      total_pages: 680
      base_file: v007.txt
    1009a74e9f4e4f98a7cc0b7a52e697e7:
      image_group_id: I00EGS1016907
      title: ''
      volume_number: 8
      total_pages: 624
      base_file: v008.txt
    3fdda80539c74ca39cff684997935eb1:
      image_group_id: I00EGS1016908
      title: ''
      volume_number: 9
      total_pages: 802
      base_file: v009.txt
    25a90bddd04a42d2a5d8757f81c3b358:
      image_group_id: I00EGS1016909
      title: ''
      volume_number: 10
      total_pages: 650
      base_file: v010.txt
    9a15c90e18ea4e378d23f1fa30a57520:
      image_group_id: I00EGS1016910
      title: ''
      volume_number: 11
      total_pages: 638
      base_file: v011.txt
    9c2f045219b24ab5b764a510654eda4b:
      image_group_id: I00EGS1016911
      title: ''
      volume_number: 12
      total_pages: 686
      base_file: v012.txt
    eb7a439ede1f4415928b8066cddc930f:
      image_group_id: I00EGS1016912
      title: ''
      volume_number: 13
      total_pages: 744
      base_file: v013.txt
    846283cc973c4f77af92926ee5a2e57c:
      image_group_id: I00EGS1016913
      title: ''
      volume_number: 14
      total_pages: 762
      base_file: v014.txt
    a43b42c3fb044a0688cc2f699581785b:
      image_group_id: I00EGS1016914
      title: ''
      volume_number: 15
      total_pages: 806
      base_file: v015.txt
    8e233aef0f2041dab701a0acaeb49a02:
      image_group_id: I00EGS1016915
      title: ''
      volume_number: 16
      total_pages: 686
      base_file: v016.txt
    013f793d22e648d4a5b081018b11c4df:
      image_group_id: I00EGS1016916
      title: ''
      volume_number: 17
      total_pages: 674
      base_file: v017.txt
    e1aa4d7d724149a8923e4b20f3706874:
      image_group_id: I00EGS1016917
      title: ''
      volume_number: 18
      total_pages: 760
      base_file: v018.txt
    b631fd98421845e6b3b1442b20e3eadd:
      image_group_id: I00EGS1016918
      title: ''
      volume_number: 19
      total_pages: 908
      base_file: v019.txt
    3c194017b3f0449b972f8672ed41095a:
      image_group_id: I00EGS1016919
      title: ''
      volume_number: 20
      total_pages: 672
      base_file: v020.txt
    c73af3e58f2f4cc796a4cbe911bdf636:
      image_group_id: I00EGS1016920
      title: ''
      volume_number: 21
      total_pages: 410
      base_file: v021.txt
    97a4b108081d4ad4bc0591374d4e70d1:
      image_group_id: I00EGS1016921
      title: ''
      volume_number: 22
      total_pages: 648
      base_file: v022.txt
    902ca12835a94b6e844df7060a1e5763:
      image_group_id: I00EGS1016922
      title: ''
      volume_number: 23
      total_pages: 600
      base_file: v023.txt
    1a249eac533147db9b91d02c98e2fdec:
      image_group_id: I00EGS1016923
      title: ''
      volume_number: 24
      total_pages: 378
      base_file: v024.txt
